DROP TABLE IF EXISTS CLIENT_ADDRESS CASCADE;
DROP TABLE IF EXISTS STATE_TRANSITIONS CASCADE;
DROP TABLE IF EXISTS VEHICLE CASCADE;
DROP TABLE IF EXISTS DELIVERY CASCADE;
DROP TABLE IF EXISTS WARPER CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS STORE CASCADE;